!GuiConfig
ips: !IpConfigs
  enable_ip4: true
  enable_ip6: true
  ip4: 10.0.0.0
  ip4s:
    - 10.0.0.0
    - 192.168.0.0
    - 172.16.0.0
  ip6: '2001::'
  ip6s:
    - '2001::'
    - '2002::'
    - 'a::'
location: !LocationConfig
  alt: 2.0
  lat: 47.5791667
  lon: -122.132322
  scale: 150.0
  x: 0.0
  y: 0.0
  z: 0.0
mac: 00:00:00:aa:00:00
node_commands:
  - !NodeCommand
    cmd: wireshark
    name: Wireshark
nodes: []
observers: []
preferences: !PreferencesConfig
  editor: vim
  gui3d: /usr/local/bin/std3d.sh
  height: 750
  terminal: kitty
  theme: black
  width: 1000
recentfiles: []
scale: 1.0
servers: []